import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

describe('Studio 预设工作台源码契约', () => {
  it('接入独立导航、CRUD、CodeMirror 表达式装饰和跨页证据意图', () => {
    const page = readFileSync(resolve('client/workspace/page.vue'), 'utf8')
    const workspace = readFileSync(resolve('client/preset/workspace.vue'), 'utf8')
    const editor = readFileSync(resolve('client/preset/source-editor.vue'), 'utf8')
    const sourceExpressions = readFileSync(resolve('client/preset/source-expressions.ts'), 'utf8')
    const modelRequests = readFileSync(resolve('client/model-request/workspace.vue'), 'utf8')
    const trajectory = readFileSync(resolve('client/model-request/trajectory.vue'), 'utf8')
    const shell = readFileSync(resolve('client/workspace/shell.ts'), 'utf8')
    const navigation = readFileSync(resolve('client/shared/evidence-navigation.ts'), 'utf8')
    const styles = readFileSync(resolve('client/preset/styles.css'), 'utf8')

    expect(page).toContain('IconFileCode')
    expect(page).toContain("shell.selectView('presets')")
    expect(page).toContain('<PresetWorkspace')
    expect(page).toContain(':navigation="shell.evidenceNavigation"')
    expect(page).toContain('@read-request="settleReadRequest"')
    expect(workspace).toContain("kind === 'core' ? 'ChatLuna' : 'Character'")
    expect(workspace).toContain('ChatLuna 预设')
    expect(workspace).toContain('Character')
    expect(workspace).toContain('新建预设')
    expect(workspace).toContain('重命名预设')
    expect(workspace).toContain('删除预设')
    expect(workspace).toContain('放弃未保存修改？')
    expect(workspace).toContain("requestDirtyAction('delete')")
    expect(workspace).toContain("emit('navigateEvidence', result, captureOrigin())")
    expect(workspace).not.toContain('打开模型请求证据')
    expect(workspace).toContain('预设已被其他位置修改')
    expect(workspace).toContain('v-if="showSaveStatus"')
    expect(workspace).not.toContain('formatBytes(document.size)')
    expect(workspace).not.toContain("return dirty.value ? '有未保存修改' : '已保存'")
    expect(workspace).not.toContain('chatluna-studio-preset-context-bar')
    expect(workspace).not.toContain('选择证据定位机器人')
    expect(workspace).not.toContain('当前没有活动逻辑会话')
    expect(workspace).not.toContain('群聊中有多个虚拟机器人')
    expect(workspace).not.toContain('botId: evidenceContext.value.botId')
    expect(workspace).not.toContain('conversationId: evidenceContext.value.conversationId')
    expect(shell).not.toContain('resolvePresetEvidenceBots')
    expect(shell).not.toContain('selectPresetEvidenceBot')
    expect(shell).not.toContain('selectedPresetBotId')
    expect(workspace).toContain('<SelectGroup>')
    expect(workspace).not.toContain('parseDocument')
    expect(workspace).not.toContain('YAML.parse')
    expect(workspace).toContain(':kind="document.kind"')
    expect(editor).toContain("from '@codemirror/lang-yaml'")
    expect(editor).toContain('HighlightStyle.define')
    expect(editor).toContain('syntaxHighlighting(presetHighlightStyle)')
    expect(editor).toContain('EditorView.theme')
    expect(editor).toContain('Decoration.mark')
    expect(editor).toContain('hoverTooltip')
    expect(editor).toContain("'查看模型请求'")
    expect(editor).toContain("h(Button, {")
    expect(editor).toContain("size: 'xs'")
    expect(editor).toContain("variant: 'ghost'")
    expect(editor).toContain("class: 'chatluna-studio-preset-expression-tooltip-link'")
    expect(editor).toContain('header.append(label, action)')
    expect(editor).toContain('IconExternalLink')
    expect(editor).toContain("onClick: () => emit('expressionClick'")
    expect(editor).not.toContain('EditorView.domEventHandlers')
    expect(editor).not.toContain("role: 'button'")
    expect(editor).not.toContain("tabindex: '0'")
    expect(editor).toContain('result.value')
    expect(workspace).toContain('resolvePresetExpressionObservedValue')
    expect(editor).toContain("source[sourceFrom] !== '{' || source[sourceTo - 1] !== '}'")
    expect(editor).toContain('codeMirrorOffset(source, sourceFrom)')
    expect(editor).toContain("expression.kind === 'control'")
    expect(editor).toContain('expression.clickable && expression.stableId')
    expect(editor).toContain('resolvePresetSourceExpressions')
    expect(editor).not.toContain('? expressionDecorations(props.expressions)')
    expect(editor).toContain("isUserEvent('input')")
    expect(editor).toContain('syncDocument.of(true)')
    expect(editor).toContain('setDecorations.of(expressionDecorations(value, activeExpressions))')
    expect(editor).toContain("emit('update:modelValue'")
    expect(editor).toContain('scrollSnapshot')
    expect(editor).toContain('toRaw(props.scrollTo)')
    expect(editor).toContain('captureScrollSnapshot')
    expect(editor).toContain('defineExpose')
    expect(editor).toContain('markRaw')
    expect(editor).toContain('view.dispatch({ effects: scrollTo })')
    expect(workspace).toContain('captureOrigin')
    expect(workspace).toContain('listScrollTop')
    expect(workspace).toContain('createScrollRestore')
    expect(workspace).toContain('originRestore')
    expect(workspace).toContain('markRaw')
    expect(workspace).toContain('shallowRef')
    // 原点快照携带 CodeMirror StateEffect；导航 module 用 shallowRef 持有，不做深层响应式转换。
    expect(navigation).toContain('shallowRef')
    expect(navigation).not.toContain('deepRef')
    expect(page).toContain(':origin-restore="shell.evidenceNavigation.presetOriginRestore.value"')
    expect(shell).toContain('evidenceNavigation.returnToPresetOrigin()')
    // 返回预设原点直接落回预设视图，不经过脏值守卫：那一刻要恢复的正是被守卫保护的那份草稿。
    expect(shell).toContain("currentView.value = 'presets'")
    expect(sourceExpressions).toContain("from '../../src/presets/source-document'")
    expect(sourceExpressions).toContain('parsePresetSourceDocument(input.kind, input.source)')
    expect(sourceExpressions).toContain('if (input.source === input.loadedSource) return input.serverExpressions')
    expect(sourceExpressions).toContain('clickable: false')
    expect(modelRequests).toContain('navigation: EvidenceNavigation')
    expect(modelRequests).toContain('showEvidenceAnalysis()')
    expect(modelRequests).toContain("mode: 'request'")
    expect(modelRequests).toContain("@locate-result=\"completeNavigationLocate\"")
    expect(modelRequests).toContain('navigationFailure')
    expect(trajectory).toContain('const analysisLocateRequest = computed(() => props.externalLocate ?? internalAnalysisLocateRequest.value)')
    expect(trajectory).toContain('externalLocate?: LocateRequest')
    expect(styles).toContain('.chatluna-studio-preset-expression.is-control')
    expect(styles).toContain('.chatluna-studio-preset-expression.is-value')
    expect(styles).toContain('.chatluna-studio-preset-expression-tooltip-value')
    expect(styles).toContain('.chatluna-studio-preset-expression-tooltip-header')
    expect(styles).toContain('.chatluna-studio-preset-expression-tooltip-action')
    expect(styles).toContain('.chatluna-studio-preset-expression-tooltip-link')
    expect(styles).toContain('body[data-chatluna-studio-frosted] .chatluna-studio-preset-source-editor .cm-tooltip')
    expect(workspace).toContain('class="chatluna-studio-preset-editor-overlay chatluna-studio-overlay-header"')
    expect(workspace).toContain('ref="editorOverlayElement"')
    expect(styles).toMatch(/\.chatluna-studio-preset-editor-overlay\s*\{[^}]*position:\s*absolute;[^}]*--chatluna-studio-overlay-header-surface:\s*var\(--chatluna-studio-surface\)/s)
    expect(styles).toMatch(/\.chatluna-studio-preset-source-editor \.cm-scroller\s*\{[^}]*padding-top:\s*var\(--chatluna-studio-preset-overlay-height/s)
    expect(styles).toMatch(/body\[data-chatluna-studio-frosted\] \.chatluna-studio-preset-source-editor \.cm-tooltip\s*\{[^}]*background:\s*color-mix\(in srgb, var\(--chatluna-studio-panel\) 72%, transparent\)/s)
    expect(styles).toMatch(/body\[data-chatluna-studio-frosted\] \.chatluna-studio-preset-source-editor \.cm-tooltip\s*\{[^}]*backdrop-filter:\s*saturate\(180%\) blur\(20px\)/s)
    expect(styles).toMatch(/\.chatluna-studio-preset-expression-tooltip-header\s*\{[^}]*justify-content:\s*space-between/s)
    expect(styles).toMatch(/\.chatluna-studio-preset-expression-tooltip-action \.chatluna-studio-preset-expression-tooltip-link\s*\{[^}]*height:\s*24px/s)
    expect(styles).toMatch(/\.chatluna-studio-preset-expression\.is-value\s*\{[^}]*text-decoration:\s*underline;[^}]*\}/s)
    expect(styles).not.toMatch(/\.chatluna-studio-preset-expression\.is-value\s*\{[^}]*cursor:/s)
    // 区域内边距取跨区域令牌：右侧悬浮导航栏的外侧留白同源于它，各写一份字面值会让卡片悄悄偏心。
    expect(styles).toContain('padding: var(--chatluna-studio-region-padding)')
    expect(styles).toContain('grid-template-columns: minmax(280px, 360px) minmax(0, 1fr)')
    expect(styles).toContain('border-radius: 16px')
    expect(styles).toMatch(/\.chatluna-studio-preset-list-pane,\s*\n\s*\.chatluna-studio-preset-editor-pane\s*\{[^}]*display:\s*grid/s)
    expect(styles).toMatch(/\.chatluna-studio-preset-empty\s*\{[^}]*place-items:\s*center/s)
    expect(styles).toMatch(/\.chatluna-studio-preset-empty\.is-editor\s*\{[^}]*grid-row:\s*1 \/ -1/s)
    expect(styles).toContain('.chatluna-studio-preset-token-key')
    expect(styles).toContain('.chatluna-studio-workspace[data-color-mode="dark"] .chatluna-studio-preset-source-editor')
    expect(page).toContain('@return-to-preset="shell.returnToPresetOrigin"')
    // 两条入口路径共用同一份进入状态；列表选择保护随之生效，无法被某条路径遗漏。
    expect(modelRequests).toContain('function applyEntryState()')
    expect(modelRequests).toContain('beginModelRequestListNavigation(selectionState.value, state.recordId)')
    expect(modelRequests).toContain('props.navigation.preserveSelectionOnFilterChange()')
    expect(modelRequests).not.toContain('applyRequestNavigationIntent')
    expect(modelRequests).not.toContain('releaseModelRequestListNavigationGuard')
    expect(modelRequests).toContain('v-for="record in displayRecords"')
    expect(modelRequests).toContain('resolveModelRequestListRecords(')
    expect(modelRequests).toContain("'is-selected': record.id === selectedRecordId")
    expect(modelRequests).toContain(':aria-current="record.id === selectedRecordId')
    // 返回按钮的存在、文案与去向都由 returnTarget 单点派生，不再各自判断一次。
    expect(modelRequests).toContain('v-if="returnLabel"')
    expect(modelRequests).toContain(':aria-label="returnLabel"')
    expect(modelRequests).toContain("if (props.navigation.returnTarget.value === 'view') return returnToTrajectory()")
    expect(modelRequests).not.toContain('canReturnToTrajectory')
    expect(modelRequests).not.toContain('canReturnToPreset')
    expect(modelRequests).toContain('class="chatluna-studio-model-request-return"')
    expect(modelRequests).toContain("emit('returnToPreset')")
    expect(modelRequests.indexOf('chatluna-studio-model-request-actions')).toBeLessThan(modelRequests.indexOf('chatluna-studio-model-request-return'))
    expect(modelRequests.indexOf('chatluna-studio-model-request-return')).toBeLessThan(modelRequests.indexOf('chatluna-studio-model-request-detail-nav'))
    // 返回是否可用是导航 module 的响应式事实；工作台 shell 不再手工镜像它。
    expect(shell).toContain('returnToPresetOrigin')
    expect(shell).toContain('evidenceNavigation.clear()')
    // 离开模型请求视图时清掉跳转意图与回程：它们属于这一次进入。
    expect(shell).toContain("if (view !== 'model-requests') evidenceNavigation.clear()")
    expect(shell).not.toContain('canReturnFromPresetEvidence')
    expect(shell).not.toContain('presetOriginRestore')
    expect(shell).not.toContain('originRestoreSeq')
    expect(shell).not.toContain('modelRequestNavigationSeq')
  })

  it('表达式悬停值滚动条不绘制轨道背景', () => {
    const styles = readFileSync(resolve('client/preset/styles.css'), 'utf8')
    const valueRule = styles.slice(styles.indexOf('.chatluna-studio-preset-expression-tooltip-value {')).split('}')[0]
    expect(valueRule).toContain('scrollbar-color: #94a3b8 transparent')
    const trackRule = styles
      .slice(styles.indexOf('.chatluna-studio-preset-expression-tooltip-value::-webkit-scrollbar-track {'))
      .split('}')[0]
    expect(trackRule).toContain('background: transparent')
  })
})
